# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ersi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ArcGIS-Runtime-SDK-iOS', '100.0'
  pod 'PubNub', '4.1'
  pod 'Cartography', '1.0'
  pod 'lottie-ios'
end
